name: Mirror to Private Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read
  issues: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to private repository
        run: |
          git remote add private https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/EpitechPromo2028/B-OOP-400-NAN-4-1-tekspice-leonard.baraton.git
          git push private main
